import * as T from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{RoomEnvironment}from'three/addons/environments/RoomEnvironment.js';import{EffectComposer}from'three/addons/postprocessing/EffectComposer.js';import{RenderPass}from'three/addons/postprocessing/RenderPass.js';import{UnrealBloomPass}from'three/addons/postprocessing/UnrealBloomPass.js';import{OutputPass}from'three/addons/postprocessing/OutputPass.js';import{GLTFExporter}from'three/addons/exporters/GLTFExporter.js';import{buildMouse}from'./model.js';
const $=s=>document.querySelector(s),renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;$('#stage').appendChild(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#151d1d');scene.fog=new T.FogExp2('#151d1d',.035);const camera=new T.PerspectiveCamera(36,innerWidth/innerHeight,.1,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=1.5;controls.minDistance=2.5;controls.maxDistance=15;
function reset(){const mobile=innerWidth<800;camera.position.set(2.5,1.8,mobile?6.7:4.4);controls.target.set(0,.65,0);camera.setViewOffset(innerWidth,innerHeight,mobile?0:innerWidth*.07,mobile?innerHeight*.16:0,innerWidth,innerHeight);controls.update();}reset();
const pm=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pm.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=.30;room.dispose();pm.dispose();scene.add(new T.HemisphereLight(0xcbefff,0x202337,1.1));const key=new T.DirectionalLight(0xecf4ff,2.0);key.position.set(-3,6,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const rim=new T.DirectionalLight(0xc496ff,1.5);rim.position.set(3,3,-4);scene.add(rim);
const floor=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshStandardMaterial({color:0x202b29,roughness:1,metalness:0}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
const grid=new T.GridHelper(12,40,0x244f64,0x1c3449);grid.position.y=.006;grid.visible=false;scene.add(grid);
// A physical miniature landscape anchors the digital animal in CARAKURI.
// The stage is bare: no scattered rocks, no standing lantern — PIP carries its own light.
// A bare floor: the scattered rocks, the moss ring and the standing lantern are gone.
const mouse=buildMouse();scene.add(mouse.root);const mixer=new T.AnimationMixer(mouse.root);let motion='Idle',action=mixer.clipAction(mouse.clips[0]);action.play();let time=0,frames=0,speed=1,paused=false,delivery=null,count=0,strafe=null;
const target=new T.Mesh(new T.TorusGeometry(.30,.012,8,48),new T.MeshStandardMaterial({color:0xb8fff4,emissive:0x42ffd2,emissiveIntensity:3}));target.rotation.x=-Math.PI/2;target.position.set(1.5,.02,0);target.visible=false;scene.add(target);
// No motion trail: PIP runs on its own light, without a wake.
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.4,.5,1.5));composer.addPass(new OutputPass());
function setMotion(n){const next=mixer.clipAction(mouse.clips.find(c=>c.name===n));next.reset().play();if(next!==action)action.crossFadeTo(next,.18,true);action=next;motion=n;document.querySelectorAll('[data-motion]').forEach(b=>{b.classList.toggle('active',b.dataset.motion===n);b.setAttribute('aria-pressed',String(b.dataset.motion===n))});$('#status').textContent={Idle:'信号を待っています',Run:'パケットを運んでいます',Dash:'高速で駆け抜けています'}[n];}
document.querySelectorAll('[data-motion]').forEach(b=>b.onclick=()=>{strafe=null;delivery=null;target.visible=false;setMotion(b.dataset.motion)});$('#speed').oninput=e=>{speed=Number(e.target.value);$('#speed-value').value=speed+'×'};$('#pause').onchange=e=>paused=e.target.checked;$('#rotate').onchange=e=>controls.autoRotate=e.target.checked;$('#reset').onclick=reset;$('#collapse').onclick=()=>{$('#settings').hidden=!$('#settings').hidden};$('#deliver').onclick=()=>{strafe=null;delivery={start:time,from:mouse.root.position.clone()};target.visible=true;setMotion('Dash');};
document.querySelectorAll('[data-strafe]').forEach(b=>b.onclick=()=>{delivery=null;target.visible=false;const side=Number(b.dataset.strafe);strafe={side,start:time,from:mouse.root.position.clone(),delta:new T.Vector3(side*.85,0,0).applyQuaternion(mouse.root.quaternion)};setMotion('Run');});
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}$('#capture').onclick=()=>renderer.domElement.toBlob(b=>download(b,'PIP.png'));$('#export').onclick=async()=>{const b=$('#export');b.disabled=true;try{download(new Blob([await new GLTFExporter().parseAsync(mouse.root,{binary:true,animations:mouse.clips})]),'PIP-animated.glb')}finally{b.disabled=false}};
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(!paused){time+=dt*speed;mixer.update(dt*speed);mouse.tick(time,motion,strafe?.side||0);if(strafe){const f=Math.min(1,(time-strafe.start)/.65);mouse.root.position.copy(strafe.from).addScaledVector(strafe.delta,f*f*(3-2*f));if(f===1){strafe=null;setMotion('Idle');}}else if(delivery){const f=Math.min(1,(time-delivery.start)/.65);mouse.root.position.lerpVectors(delivery.from,new T.Vector3(1.5,0,0),f);const d=new T.Vector3(1.5,0,0).sub(delivery.from);mouse.root.rotation.y=Math.atan2(d.x,d.z);if(f===1){delivery=null;target.visible=false;setMotion('Idle');$('#status').textContent='配送完了 · '+(++count)+' packets';}}else if(motion!=='Idle'&&$('#travel').checked){const a=time*(motion==='Dash'?2.3:.9);mouse.root.position.set(Math.sin(a)*1.15,0,Math.sin(a*2)*.42);mouse.root.rotation.y=Math.atan2(Math.cos(a)*1.15,Math.cos(a*2)*.84);}}controls.update();composer.render();frames++;});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);reset()});if(matchMedia('(prefers-reduced-motion: reduce)').matches){paused=true;$('#pause').checked=true;}window.pip={mouse,mixer,scene,camera,controls,setMotion,get state(){return{frames,motion,count,paused}}};
