
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';import {GTAOPass} from 'three/addons/postprocessing/GTAOPass.js';import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import * as T from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{RoomEnvironment}from'three/addons/environments/RoomEnvironment.js';import{GLTFExporter}from'three/addons/exporters/GLTFExporter.js';import{buildVault}from'./model.js';
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.toneMappingExposure=.85;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;document.body.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color(0x182635);const camera=new T.PerspectiveCamera(40,innerWidth/innerHeight,.1,100);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,5.4,0);controls.enableDamping=true;controls.maxPolarAngle=1.53;controls.minDistance=3;controls.maxDistance=65;function front(){camera.position.set(16,10.8,35);if(innerWidth<600)camera.position.set(30,21,63);controls.update();}front();
const pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.25;scene.add(new T.HemisphereLight(0xc5dced,0x4c3625,.38));const sun=new T.DirectionalLight(0xffdfad,2.3);sun.position.set(-5,10,6);sun.castShadow=true;sun.shadow.mapSize.set(4096,4096);Object.assign(sun.shadow.camera,{left:-17,right:17,top:17,bottom:-17});scene.add(sun);const rim=new T.DirectionalLight(0x709bd9,2);rim.position.set(4,7,-6);scene.add(rim);
const depot=buildVault();scene.add(depot.root);const floor=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshStandardMaterial({color:0x202c31,roughness:.85}));floor.rotation.x=-Math.PI/2;floor.position.y=-.28;floor.receiveShadow=true;scene.add(floor);
let paused=false,t=0;document.querySelector('#energy').oninput=e=>depot.setEnergy(Number(e.target.value)/100);document.querySelector('#cut').onchange=e=>depot.setOpen(e.target.checked);let closing=false;const openButton=document.querySelector('#vault-open'),closeButton=document.querySelector('#vault-close'),vaultStatus=document.querySelector('#vault-status');function operateVault(close){closing=close;paused=false;document.querySelector('#pause').checked=false;depot.setLock(close);}openButton.onclick=()=>operateVault(false);closeButton.onclick=()=>operateVault(true);document.querySelector('#pause').onchange=e=>paused=e.target.checked;document.querySelector('#front').onclick=front;document.querySelector('#back').onclick=()=>{camera.position.set(-22,14,-30);controls.update();};document.querySelector('#export').onclick=async e=>{e.target.disabled=true;try{const exportRoot=depot.root.clone(true);exportRoot.traverse(o=>{if(o.isMesh&&o.material.isShaderMaterial)o.material=new T.MeshStandardMaterial({color:0xffb944,emissive:0xffa321,emissiveIntensity:2,transparent:true,opacity:.55});});const data=await new GLTFExporter().parseAsync(exportRoot,{binary:true,onlyVisible:false});const u=URL.createObjectURL(new Blob([data]));const a=document.createElement('a');a.href=u;a.download='CARAKURI-Treasury-Citadel.glb';a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);}finally{e.target.disabled=false;}};
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const ao=new GTAOPass(scene,camera,innerWidth,innerHeight);const aoRender=ao.render.bind(ao);ao.render=(...args)=>{const hidden=[];depot.root.traverse(o=>{if(o.name==='ContinuousFurnaceSteam'&&o.visible){hidden.push(o);o.visible=false;}});try{aoRender(...args);}finally{hidden.forEach(o=>o.visible=true);}};composer.addPass(ao);composer.addPass(new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.28,.4,1.0));composer.addPass(new OutputPass());const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(!paused){t+=dt;depot.tick(t,dt,camera);}const fraction=depot.getStats().lockOpen;const status=fraction<.002?'閉鎖・ロック完了':fraction>.998?'開放':paused?'開閉を一時停止':closing?'歯車駆動 · 閉鎖中':'歯車駆動 · 開放中';if(vaultStatus.textContent!==status)vaultStatus.textContent=status;openButton.disabled=!closing&&fraction>.998;closeButton.disabled=closing&&fraction<.002;controls.update();composer.render();});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);});window.depot={...depot,scene,camera,renderer};
