
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';import {GTAOPass} from 'three/addons/postprocessing/GTAOPass.js';import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import * as T from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{RoomEnvironment}from'three/addons/environments/RoomEnvironment.js';import{GLTFExporter}from'three/addons/exporters/GLTFExporter.js';import{buildGate}from'./model.js';
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;document.body.prepend(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color(0x18232b);const camera=new T.PerspectiveCamera(40,innerWidth/innerHeight,.1,100);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,3.05,0);controls.enableDamping=true;controls.maxPolarAngle=1.53;controls.minDistance=3;controls.maxDistance=30;function front(){camera.position.set(10,7.2,15);controls.update();}front();
const pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromScene(new RoomEnvironment(),.04).texture;scene.environmentIntensity=.25;scene.add(new T.HemisphereLight(0xc5dced,0x4c3625,.38));const sun=new T.DirectionalLight(0xffdfad,2.3);sun.position.set(-5,10,6);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-8,right:8,top:9,bottom:-8});scene.add(sun);const rim=new T.DirectionalLight(0x709bd9,2);rim.position.set(4,7,-6);scene.add(rim);
const depot=buildGate();scene.add(depot.root);const floor=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshStandardMaterial({color:0x202c31,roughness:.85}));floor.rotation.x=-Math.PI/2;floor.position.y=-.28;floor.receiveShadow=true;scene.add(floor);
let paused=false,t=0;document.querySelector('#cut').onchange=e=>depot.setOpen(e.target.checked);document.querySelector('#pause').onchange=e=>paused=e.target.checked;document.querySelector('#front').onclick=front;document.querySelector('#back').onclick=()=>{camera.position.set(-10,7,-12);controls.update();};document.querySelector('#export').onclick=async e=>{e.target.disabled=true;try{const data=await new GLTFExporter().parseAsync(depot.root,{binary:true,onlyVisible:false});const u=URL.createObjectURL(new Blob([data]));const a=document.createElement('a');a.href=u;a.download='CARAKURI-SPO-watchgate.glb';a.click();setTimeout(()=>URL.revokeObjectURL(u),10000);}finally{e.target.disabled=false;}};
document.querySelector('#health').oninput=e=>{depot.setHealth(Number(e.target.value));document.querySelector('#health-value').textContent=e.target.value+'/3';};const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const ao=new GTAOPass(scene,camera,innerWidth,innerHeight);composer.addPass(ao);composer.addPass(new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.28,.4,1.0));composer.addPass(new OutputPass());const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(!paused){t+=dt;depot.tick(t,dt);}controls.update();composer.render();});addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);});window.depot={...depot,scene,camera};
