// The characters of the series. Single source of truth for the hub and the switcher.
// crop: the region of preview.png (1600x1100) the hub card shows, all at a 3:4 aspect
// so the four figures read at the same size. zoom trims that by eye afterwards:
// NOMAD has the heaviest build of the four and still read large at parity.
export const SERIES = [
  {
    id: 'nomad',
    crop: {x: 325, y: 43, w: 780, h: 1040},
    zoom: 0.86,
    no: '01',
    name: 'NOMAD',
    role: 'FIELD COMPANION',
    eyebrow: 'LITTLE WANDERER',
    title: '灯りを運ぶ旅人。',
    tagline: '遠回りも、悪くない。',
    accent: '#d8b669',
  },
  {
    id: 'ward',
    crop: {x: 381, y: 81, w: 731, h: 975},
    no: '02',
    name: 'WARD',
    role: 'RELAY GUARDIAN',
    eyebrow: 'KEEP THE CHAIN ALIVE',
    title: 'リレーの番人。',
    tagline: '一つひとつの灯を、守る。',
    accent: '#7fb4dd',
  },
  {
    id: 'quorum',
    crop: {x: 460, y: 254, w: 551, h: 735},
    no: '03',
    name: 'QUORUM',
    role: 'MANDATE KEEPER',
    eyebrow: 'POWER IS DELEGATED',
    title: '委任の書記官。',
    tagline: '託された声が、力になる。',
    accent: '#b28fd0',
  },
  {
    id: 'lex',
    crop: {x: 440, y: 244, w: 557, h: 742},
    no: '04',
    name: 'LEX',
    role: 'CONSTITUTION KEEPER',
    eyebrow: 'ILLUMINATE THE CONSTITUTION',
    title: '知識の灯守。',
    tagline: '憲法を携え、判断の基準を守る。',
    accent: '#e0cb87',
  },
  {
    id: 'catalyst',
    crop: {x: 489, y: 371, w: 443, h: 590},
    no: '05',
    name: 'CATALYST',
    role: 'PROJECT BUILDER',
    eyebrow: 'FUNDED TO BUILD',
    title: '築く者。',
    tagline: '受け取った資金が、形になる。',
    accent: '#e08d4f',
  },
  {
    id: 'treasury',
    crop: {x: 470, y: 313, w: 482, h: 643},
    no: '06',
    name: 'TREASURY',
    role: 'TREASURY KEEPER',
    eyebrow: 'POWERED BY DREPS',
    title: '国庫の器。',
    tagline: '吸い上げた声が、エネルギーになる。',
    accent: '#6fd2f2',
  },
  {
    id: 'pip',
    // A wider box than parity would give: PIP is the small one, and the card
    // lets it read that way instead of scaling it up to the others.
    crop: {x: 424, y: 164, w: 540, h: 720},
    no: '07',
    name: 'PIP',
    role: 'TRANSACTION COURIER',
    eyebrow: 'SMALL BODY. FAST DELIVERY.',
    title: '光の、はこび屋。',
    tagline: '小さな一歩が、世界をつなぐ。',
    accent: '#e2705f',
  },
  {
    id: 'forge',
    // Framed a little right of the body so a few links of the chain come with it:
    // the chain is half of what this one is.
    crop: {x: 357, y: 272, w: 570, h: 760},
    no: '08',
    name: 'FORGE',
    role: 'BLOCK FORGER',
    eyebrow: 'ONE BLOCK, EVERY SLOT',
    title: 'まとめて、刻む者。',
    tagline: '運ばれた記録が、ひとつの塊になる。',
    accent: '#79c9a4',
  },
];
