import * as T from 'three';import{OrbitControls}from'three/addons/controls/OrbitControls.js';import{RoomEnvironment}from'three/addons/environments/RoomEnvironment.js';import{EffectComposer}from'three/addons/postprocessing/EffectComposer.js';import{RenderPass}from'three/addons/postprocessing/RenderPass.js';import{UnrealBloomPass}from'three/addons/postprocessing/UnrealBloomPass.js';import{OutputPass}from'three/addons/postprocessing/OutputPass.js';import{GLTFExporter}from'three/addons/exporters/GLTFExporter.js';import{buildNox}from'./model.js';
const $=s=>document.querySelector(s),renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;$('#stage').appendChild(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#12141f');scene.fog=new T.FogExp2('#12141f',.035);const camera=new T.PerspectiveCamera(36,innerWidth/innerHeight,.1,100),controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.maxPolarAngle=1.5;controls.minDistance=2.5;controls.maxDistance=15;
function reset(){const mobile=innerWidth<800;camera.position.set(2.6,1.7,mobile?7.0:4.8);controls.target.set(0,.75,0);camera.setViewOffset(innerWidth,innerHeight,mobile?0:innerWidth*.07,mobile?innerHeight*.16:0,innerWidth,innerHeight);controls.update();}reset();
const pm=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pm.fromScene(room,.04);scene.environment=env.texture;scene.environmentIntensity=.22;room.dispose();pm.dispose();scene.add(new T.HemisphereLight(0xaab4e8,0x141726,1.0));const key=new T.DirectionalLight(0xdfe6ff,1.5);key.position.set(-3,6,4);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const rim=new T.DirectionalLight(0x939bf0,1.6);rim.position.set(3,3,-4);scene.add(rim);
const floor=new T.Mesh(new T.PlaneGeometry(100,100),new T.MeshStandardMaterial({color:0x181b2a,roughness:1,metalness:0}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);
// A bare midnight floor. NOX brings its own covered light; nothing else stands on the stage.
const figure=buildNox();scene.add(figure.root);const mixer=new T.AnimationMixer(figure.root);let motion='Idle',action=mixer.clipAction(figure.clips[0]);action.play();let time=0,frames=0,speed=1,paused=false,count=0,proving=null;
// The proof sigil: a ring of light that rises from the ground and fades. The lantern never opens.
const sigil=new T.Group();sigil.visible=false;scene.add(sigil);
const sigilMat=new T.MeshStandardMaterial({color:0xd7dbff,emissive:0x939bf0,emissiveIntensity:3,transparent:true,opacity:1});
{const outer=new T.Mesh(new T.TorusGeometry(.42,.010,10,64),sigilMat);outer.rotation.x=-Math.PI/2;sigil.add(outer);
 const inner=new T.Mesh(new T.TorusGeometry(.29,.006,8,48),sigilMat);inner.rotation.x=-Math.PI/2;sigil.add(inner);
 for(let j=0;j<9;j++){const a=j/9*Math.PI*2;const tick=new T.Mesh(new T.BoxGeometry(.012,.002,.075),sigilMat);tick.position.set(Math.sin(a)*.355,0,Math.cos(a)*.355);tick.rotation.y=a;sigil.add(tick);}
 sigil.children.forEach(c=>c.castShadow=false);}
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.5,.5,1.4));composer.addPass(new OutputPass());
function setMotion(n){const next=mixer.clipAction(figure.clips.find(c=>c.name===n));next.reset().play();if(next!==action)action.crossFadeTo(next,.35,true);action=next;motion=n;document.querySelectorAll('[data-motion]').forEach(b=>{b.classList.toggle('active',b.dataset.motion===n);b.setAttribute('aria-pressed',String(b.dataset.motion===n))});$('#status').textContent={Idle:'静かに漂っています',Drift:'夜を渡っています'}[n];}
document.querySelectorAll('[data-motion]').forEach(b=>b.onclick=()=>setMotion(b.dataset.motion));$('#speed').oninput=e=>{speed=Number(e.target.value);$('#speed-value').value=speed+'×'};$('#pause').onchange=e=>paused=e.target.checked;$('#rotate').onchange=e=>controls.autoRotate=e.target.checked;$('#reset').onclick=reset;$('#collapse').onclick=()=>{$('#settings').hidden=!$('#settings').hidden};
$('#prove').onclick=()=>{if(proving)return;proving={start:time};sigil.position.set(figure.root.position.x,.02,figure.root.position.z);sigil.visible=true;$('#status').textContent='証明を編んでいます…';};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}$('#capture').onclick=()=>renderer.domElement.toBlob(b=>download(b,'NOX.png'));$('#export').onclick=async()=>{const b=$('#export');b.disabled=true;try{download(new Blob([await new GLTFExporter().parseAsync(figure.root,{binary:true,animations:figure.clips})]),'NOX-animated.glb')}finally{b.disabled=false}};
const clock=new T.Clock();renderer.setAnimationLoop(()=>{const dt=Math.min(clock.getDelta(),.05);if(!paused){time+=dt*speed;mixer.update(dt*speed);
 let proof=0;
 if(proving){const f=(time-proving.start)/2.2;proof=Math.sin(Math.min(1,f)*Math.PI);sigil.position.y=.02+f*.9;sigil.rotation.y=f*1.8;sigilMat.opacity=1-f*f;sigilMat.emissiveIntensity=3*(1-f*.6);if(f>=1){proving=null;sigil.visible=false;sigilMat.opacity=1;$('#status').textContent='証明完了 · '+(++count)+' proofs';}}
 figure.tick(time,motion,proof);
 if(motion==='Drift'&&$('#travel').checked&&!proving){const a=time*.32;figure.root.position.set(Math.sin(a)*1.25,0,Math.sin(a*2)*.48);figure.root.rotation.y=Math.atan2(Math.cos(a)*1.25,Math.cos(a*2)*.96);}
}controls.update();composer.render();frames++;});
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);reset()});if(matchMedia('(prefers-reduced-motion: reduce)').matches){paused=true;$('#pause').checked=true;}window.nox={figure,mixer,scene,camera,controls,setMotion,get state(){return{frames,motion,count,paused}}};
