import * as T from 'three';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {stoneMaterial} from '../vault/materials.js';

export const TIERS=[{id:'small',name:'小さな灯の家',w:4.4,d:4.8,h:4.5},{id:'standard',name:'石の街路邸',w:6.4,d:6,h:6.8},{id:'large',name:'回廊の住宅',w:9,d:7.6,h:8.6},{id:'whale',name:'灯冠の大邸宅',w:15,d:10,h:11.2}];
export const PORT={version:1,type:'flame-DN440',radius:.22,direction:[0,1,0],units:'metres'};
export function palette(){return {stone:stoneMaterial(),joint:new T.MeshStandardMaterial({color:0x746c5e,roughness:1}),iron:new T.MeshStandardMaterial({color:0x172129,metalness:.73,roughness:.4}),copper:new T.MeshStandardMaterial({color:0x815334,metalness:.72,roughness:.36}),light:new T.MeshStandardMaterial({color:0xffd688,emissive:0xffa52d,emissiveIntensity:2}),wood:new T.MeshStandardMaterial({color:0x352d25,roughness:.83}),leaf:new T.MeshStandardMaterial({color:0x48563c,roughness:1})};}
export function kit(parent,M){
 const mesh=(geo,mat,x=0,y=0,z=0,p=parent)=>{const o=new T.Mesh(geo,mat);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);return o;};
 const box=(mat,x,y,z,w,h,d,p=parent)=>mesh(new T.BoxGeometry(w,h,d),mat,x,y,z,p);
 const rod=(a,b,r,mat=M.copper,p=parent)=>{a=new T.Vector3(...a);b=new T.Vector3(...b);const delta=b.clone().sub(a);if(delta.length()<1e-6)return;const o=mesh(new T.CylinderGeometry(r,r,delta.length(),12),mat,0,0,0,p);o.position.copy(a).add(b).multiplyScalar(.5);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),delta.normalize());return o;};
 const ring=(x,y,z,r,mat=M.copper,p=parent)=>mesh(new T.TorusGeometry(r,.045,6,32),mat,x,y,z,p);
 function collar(a,axis,r=.22){const o=rod(new T.Vector3(...a).addScaledVector(new T.Vector3(...axis),-.07).toArray(),new T.Vector3(...a).addScaledVector(new T.Vector3(...axis),.07).toArray(),r*1.3,M.iron);const basis=new T.Vector3(...axis);const u=new T.Vector3(Math.abs(basis.y)>.9?1:0,Math.abs(basis.y)>.9?0:1,0).cross(basis).normalize(),v=basis.clone().cross(u);for(let i=0;i<8;i++){const pos=new T.Vector3(...a).addScaledVector(u,Math.cos(i*Math.PI/4)*r*1.16).addScaledVector(v,Math.sin(i*Math.PI/4)*r*1.16);mesh(new T.SphereGeometry(.028,6,4),M.copper,...pos.toArray());}return o;}
 function masonry(x,y,z,w,h,d){box(M.joint,x,y+h/2,z,w,h,d);const rows=Math.ceil(h/.34);for(let j=0;j<rows;j++){const hh=h/rows-.018,yy=y+(j+.5)*h/rows;for(const s of [-1,1]){for(let l=-w/2;l<w/2-.001;){const ww=Math.min(j%2&&l===-w/2?.31:.64,w/2-l);box(M.stone,x+l+ww/2,yy,z+s*(d/2+.016),ww-.016,hh,.065);l+=ww;}for(let l=-d/2;l<d/2-.001;){const dd=Math.min(j%2&&l===-d/2?.31:.64,d/2-l);box(M.stone,x+s*(w/2+.016),yy,z+l+dd/2,.065,hh,dd-.016);l+=dd;}}}}
 function arch(x,y,z,r,thick=.18,depth=.24){const shape=new T.Shape();shape.absarc(0,0,r+thick,0,Math.PI,false);shape.absarc(0,0,r,Math.PI,0,true);shape.closePath();mesh(new T.ExtrudeGeometry(shape,{depth,bevelEnabled:false,curveSegments:18}),M.stone,x,y,z);for(let i=0;i<13;i++){const a=(i+.5)*Math.PI/13;const o=box(M.joint,x+Math.cos(a)*(r+thick*.5),y+Math.sin(a)*(r+thick*.5),z+depth+.005,.013,thick,.008);o.rotation.z=a-Math.PI/2;}}
 function window(x,bottom,z,w,h,door=false){const r=w/2,stem=h-r;const shape=new T.Shape();shape.moveTo(-r,0);shape.lineTo(r,0);shape.lineTo(r,stem);shape.absarc(0,stem,r,0,Math.PI,false);shape.closePath();mesh(new T.ShapeGeometry(shape),door?M.wood:M.light,x,bottom,z+.02);arch(x,bottom+stem,z,r);for(const s of [-1,1])box(M.stone,x+s*(r+.1),bottom+stem/2,z+.1,.2,stem,.28);box(M.stone,x,bottom-.12,z+.12,w+.5,.18,.5);for(const q of [-.27,0,.27])rod([x+q*w,bottom+.06,z+.065],[x+q*w,bottom+stem+Math.sqrt(r*r-(q*w)**2),z+.065],.025,M.iron);rod([x-r,bottom+stem*.56,z+.07],[x+r,bottom+stem*.56,z+.07],.025,M.iron);if(door){ring(x+w*.22,bottom+.9,z+.08,.085);}}
 function lantern(x,y,z,s=1){box(M.iron,x,y+.1*s,z,.48*s,.2*s,.48*s);box(M.light,x,y+.67*s,z,.25*s,.94*s,.25*s);for(const dx of [-1,1])for(const dz of [-1,1])rod([x+dx*.19*s,y+.18*s,z+dz*.19*s],[x+dx*.19*s,y+1.15*s,z+dz*.19*s],.025*s,M.copper);box(M.copper,x,y+1.18*s,z,.47*s,.1*s,.47*s);const cap=mesh(new T.SphereGeometry(.3*s,12,6,0,Math.PI*2,0,Math.PI/2),M.iron,x,y+1.22*s,z);cap.scale.y=.6;}
 function rail(x,z,w,y){for(let i=0;i<=Math.ceil(w/.35);i++)rod([x-w/2+i*w/Math.ceil(w/.35),y,z],[x-w/2+i*w/Math.ceil(w/.35),y+.75,z],.023,M.iron);rod([x-w/2,y+.75,z],[x+w/2,y+.75,z],.035);}
 return {mesh,box,rod,ring,collar,masonry,arch,window,lantern,rail};
}
// Involute external gears: shared module/20 degree pressure angle, correct pitch
// radii, half-tooth phase and inverse tooth-count speeds. No decorative overlap.
function gearGeometry(n,module=.075){const rp=n*module/2,rb=rp*Math.cos(Math.PI/9),ra=rp+module,rf=rp-1.25*module,shape=new T.Shape();const inv=r=>{const a=Math.acos(Math.min(1,rb/r));return Math.tan(a)-a;};const half=Math.PI/(2*n),ip=inv(rp),pts=[];for(let i=0;i<n;i++){const a=i*2*Math.PI/n;pts.push([rf,a-half-ip]);for(let k=0;k<=4;k++){const r=Math.max(rf,rb)+(ra-Math.max(rf,rb))*k/4;pts.push([r,a-half+inv(r)-ip]);}for(let k=4;k>=0;k--){const r=Math.max(rf,rb)+(ra-Math.max(rf,rb))*k/4;pts.push([r,a+half-inv(r)+ip]);}pts.push([rf,a+half+ip]);}pts.forEach(([r,a],i)=>shape[i?'lineTo':'moveTo'](r*Math.cos(a),r*Math.sin(a)));shape.closePath();const hole=new T.Path();hole.absarc(0,0,rp*.52,0,Math.PI*2,true);shape.holes.push(hole);return new T.ExtrudeGeometry(shape,{depth:.12,bevelEnabled:false});}
export function batchStatic(root){root.updateMatrixWorld(true);const buckets=new Map();root.traverse(o=>{if(o.isMesh&&!o.userData.dynamic){let p=o.parent;while(p!==root){if(p.userData.dynamic)return;p=p.parent;}if(!buckets.has(o.material))buckets.set(o.material,[]);buckets.get(o.material).push(o);}});const inv=root.matrixWorld.clone().invert();for(const [m,parts] of buckets){const gs=parts.map(o=>{const g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();return g.applyMatrix4(inv.clone().multiply(o.matrixWorld));});const geo=mergeGeometries(gs);gs.forEach(g=>g.dispose());if(!geo)throw Error('Geometry batching failed');const mesh=new T.Mesh(geo,m);mesh.castShadow=mesh.receiveShadow=true;root.add(mesh);parts.forEach(o=>{o.removeFromParent();o.geometry.dispose();});}}
export {gearGeometry};
export {buildResidence} from './architecture.js';
